name: project_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  config_repository:
    path: ../config_repository
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  material_repository:
    path: ../material_repository
  notification_repository:
    path: ../notification_repository
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  user_repository:
    path: ../user_repository
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
