name: user_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  dio: ^5.5.0+1
  config_repository:
    path: ../config_repository
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.2
