name: user_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  config_repository:
    path: ../config_repository
  dio: ^5.5.0+1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  log_collector:
    path: ../log_collector
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lint: ^2.3.0
  test: ^1.25.2
