name: better_player_enhanced
description: Advanced video player. It solves many typical use cases and it's easy to run.
version: 0.0.4
homepage: https://github.com/kingace2056/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.2.8
  meta: ^1.15.0
  flutter_widget_from_html_core: ^0.15.2
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.5
  collection: ^1.19.0
  xml: ^6.5.0

dev_dependencies:
  lint: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
