name: authentication_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo


publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  config_repository:
    path: ../config_repository
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  flutter_web_auth_2: ^3.1.2
  user_repository:
    path: ../user_repository
# path: ^1.8.0

dev_dependencies:
  lint: ^2.3.0
  mockito: ^5.4.4
  test: ^1.25.2
