name: config_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  cloud_firestore: ^5.4.5
  connectivity_plus: ^6.0.5
  dio: ^5.5.0+1
  firebase_core: ^3.7.0
  flutter_secure_storage: ^9.2.2
  log_collector:
    path: ../log_collector
  shared_preferences: ^2.3.2

  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
