name: config_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  log_collector:
    path: ../log_collector

  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
