name: Flutter Release

on:
  push:
    tags:
      - 'v*.*.*-alpha*'  # Match alpha version tags, e.g., v1.0.0-alpha, v1.0.0-alpha.1
      - 'v*.*.*'         # Match major version tags, e.g., v1.0.0
  # pull_request:
  #   branches:
  #     - main             # Trigger on PRs merged into the main branch

jobs:
  build-and-release:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create environment variables
      run: |
        echo "API_URL=${{ secrets.API_URL }}" >> .env
        echo "GEOAPIFY_API_KEY=${{ secrets.GEOAPIFY_API_KEY }}" >> .env
        echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> .env
        cat .env

    - name: Set up java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        check-latest: true

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build App Bundle
      run: flutter build appbundle --release

    - name: Rename release files
      run: |
        mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/craftmate-release.apk
        mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/craftmate-release.aab
    
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
            build/app/outputs/flutter-apk/craftmate-release.apk
            build/app/outputs/bundle/release/craftmate-release.aab
        draft: false
        # prerelease: ${{ contains(github.ref_name, '-alpha') }}
        generate_release_notes: true

